### ISSUE TITLE
Seperate query package for preact and react 

### ISSUE THREAD

**Issue by gaurishhs** [XantreGodlike/preact-signals#27]
Hi! is it possible to have separate query packages for react and preact `@preact-signals/query-preact` and `@preact-signals/query-react` and the core functionality which can be shared in a core package independent of the environment

**Comment by XantreGodlike** [comment]
Hi. Code of `@preact-signals/query` framework agnostic only thing you need to do: resolve `@preact/signals-react` as `@preact/signals`

**Comment by XantreGodlike** [comment]
import preact from "@preact/preset-vite";
import { defineConfig } from "vite";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [preact()],
  resolve: {
    // add this line
    dedupe: ["preact"],
    alias: [
      // ...
      // add this line
      { find: "@preact/signals-react", replacement: "@preact/signals" },
    ],
  },
});

**Comment by gaurishhs** [comment]
I get that, What i meant was to get rid-of react-dom and react. Something specially for Preact

**Comment by XantreGodlike** [comment]
Which benefits will it have? I can create separate package with rewritten imports. Is it only beneficial for simplicity of configuration?

**Comment by gaurishhs** [comment]
This will definitely reduce the bundle size. I'm open to contribute to this

**Comment by XantreGodlike** [comment]
It will has no impact on bundle size. This library uses react and react-dom as peer dependecy

**Comment by gaurishhs** [comment]
they're aliased by preact/compat which is another 2.2kb

**Comment by gaurishhs** [comment]
2.2kb isnt too big but the structure doesnt really look good at this point

**Comment by XantreGodlike** [comment]
Probably even less, since we will use `preact/hooks`. I actually don't see it really beneficial, except cases when  `query` is only user dep - in this case we will probably save less than 1 kb. I don't think this cost is acceptable for doing extra work and maintaining a separate package

**Comment by gaurishhs** [comment]
I can contribute

**Comment by gaurishhs** [comment]
Maybe you're correct. Thanks!
