### ISSUE TITLE
Type definitions not working properly. useQuery$ returning Opaque<T, "@preact-signals/utils;flatStore">

### ISSUE THREAD

**Issue by Niklas-Mezynski** [XantreGodlike/preact-signals#67]
I am having trouble with the type definitions of the package. When I use the useQuery$ function for example, it does not give any useful type information. The retuend value is of type `Opaque<T, "@preact-signals/utils;flatStore">` which is basically equal to any.
I tried it with a blank vite setup and I also tried playing around with my tsconfig but no success here.

Package versions:
```
"@preact/signals": "1.2.2"
"@preact-signals/query": "1.3.14"
"typescript": "5.2.2"
"vite": "5.0.0"
``` 

## Steps to reproduce:
Init a new project
```
npx create-vite preact-ts-query-test --template preact-ts
``` 
Add dependencies
```shell
npm i @preact/signals @preact-signals/query
```
Copy all the necessary configuration from the docs to the `vite.config.ts`.
Then try to use this inside the codebase:
```typescript
import { useQuery$ } from "@preact-signals/query";

export function App() {
  const query = useQuery$(() => ({
    //   ^? const query: Opaque<T, "@preact-signals/utils;flatStore">
    queryKey: ["user"],
    queryFn: () => Promise.resolve({ name: "John Doe" }),
  }));

  return (
    <div>...</div>
  );
}
```

**Comment by XantreGodlike** [comment]
Will try to to check this behavior today

**Comment by Niklas-Mezynski** [comment]
Yes strict is enabled. I also used the package a while ago and had no problems. I also suspect tsconfig to be the problem but could not figure out a fix. Maybe you can help otherwise I have debug a bit more.

**Comment by XantreGodlike** [comment]
I get it. It because `type-fest` was in devDependencies of `@preact-signals/utils` which query depends on
<img width="375" alt="image" src="https://github.com/XantreGodlike/preact-signals/assets/57757211/650fb8ec-89b5-49b3-ae40-ff241f831be2">

You can verify it with
```bash
npm i type-fest
```

I will provide fix soon

**Comment by Niklas-Mezynski** [comment]
Got it. Thanks for your great work!
