### ISSUE TITLE
`@preact-signals/utils` deepSignal wrong types

### ISSUE THREAD

**Issue by hiddenLadder** [XantreGodlike/preact-signals#76]
deepSignal and useDeepSignal return a signal that requires adding .value, but typescript doesn't seem to resolve that correctly.
![image](https://github.com/XantreGodlike/preact-signals/assets/89526742/eb406aa0-f6c1-4196-a4a0-e5e83d191d53)
![image](https://github.com/XantreGodlike/preact-signals/assets/89526742/44af0243-5c48-4582-b62e-da4fab066f46)

Steps to reproduce:
1) create a vite project with react-swc plugin
2) install `@preact-signals/safe-react` and `@preact-signals/utils`
3) import deepSignal

**Comment by XantreGodlike** [comment]
It's a problem with types of `@preact-signals/unified-signals` deps. Will fix soon
