### ISSUE TITLE
Testing createResource

### ISSUE THREAD

**Issue by oravecz** [XantreGodlike/preact-signals#80]
I have a resource I would like to test to ensure the expected states resolve under particular conditions. I am mocking my service call (fetcher). Is there an example that can be provided to show how a test in Jest (or Vitest) might be able to wait until a state change in the resource signal fires? Or better yet, until an error or ready state is achieved?

This capability is provided for Promises with the `.resolves.` or `.rejects.` in the Matchers API, but Signals are trailing a bit in this area.

**Comment by XantreGodlike** [comment]
This is how I've implemented tests for resource: https://github.com/XantreGodlike/preact-signals/blob/8fee2c39e486d990b344fcc852f458dee9924579/packages/utils/src/lib/resource/resource.test.ts#L147-L188
If you want to have async api you can use this snippet:
```ts
const waitFor = <T>(compute: () => { done: false; result: null; } | {done:true; result: T}, options = { timeout: 1000 }): Promise<T> => {
	let resolve: (value: T) => void | null = null
	let reject: (value: unknown) => void | null = null
	const pr = new Promise<T>((_resolve, _reject) => {
		resolve = _resolve
		reject = _reject
	})
	if (!resolve || !reject) {
		throw new Error('invariant')
	}
	let isDisposed = false
	const timeoutId = setTimeout(() => {
		reject(new Error('waitFor timeout exceeded'))
		isDisposed = true
		dispose()
	}, options.timeout)
	const dispose = effect(() => {
		if (isDisposed) {
			return
		}
		try {
			const res = compute()
			if (res.done) {
				resolve(res.result)
				clearTimeout(timeoutId)
				isDisposed = true
				pr.finally(() => dispose())
			}
		} catch (e) {
			reject(e)
			clearTimeout(timeoutId)
			isDisposed = true
			pr.finally(() => dispose())
		}
	})
	
	return pr
}
```
