### ISSUE TITLE
Too many component renderings for the first time.

### ISSUE THREAD

**Issue by qingzhoufeihu** [XantreGodlike/preact-signals#87]
I'm not sure if it's because of Next.js, preact/signals-react, or this plugin.
[@preact-signals/safe-react](https://github.com/preactjs/signals/issues/466#issuecomment-1991970053)

**Comment by XantreGodlike** [comment]
Can you create some reproduction? I have an example app with signals and it works

**Comment by qingzhoufeihu** [comment]
App component render 2 times without this plugin:@preact-signals/safe-react/swc, but 4 times with it.
![image](https://github.com/XantreGodlike/preact-signals/assets/26052806/5c9d94f4-ed56-476f-92cf-82eb936d1b0d)
![image](https://github.com/XantreGodlike/preact-signals/assets/26052806/91ae8f79-2a26-455e-8211-f770ea811cb7)

**Comment by XantreGodlike** [comment]
See it. Strange, will try to figure out why it happens

**Comment by XantreGodlike** [comment]
In vite with swc plugin it renders ones

**Comment by XantreGodlike** [comment]
Vite:
<img width="521" alt="image" src="https://github.com/XantreGodlike/preact-signals/assets/57757211/f9ac8c33-9276-49f2-bb41-063177887589">
![image](https://github.com/XantreGodlike/preact-signals/assets/57757211/13c627a4-a4d3-4238-915f-b9229203bc07)
Next: 
<img width="541" alt="image" src="https://github.com/XantreGodlike/preact-signals/assets/57757211/bbc3d270-eb59-49ce-8fb9-c9038d2d3956">
![image](https://github.com/XantreGodlike/preact-signals/assets/57757211/e7ded8f8-2ba8-4cfb-abeb-4dfb62e17cc2)

**Comment by XantreGodlike** [comment]
I can reproduce the behavior by using `useSyncExternalStore`. I will invest furhter
<img width="517" alt="image" src="https://github.com/XantreGodlike/preact-signals/assets/57757211/55d42e1e-195c-49cb-97fc-65db0b18d093">
![image](https://github.com/XantreGodlike/preact-signals/assets/57757211/ede6c002-5e41-44b8-ae8f-14516b85ebb7)

**Comment by XantreGodlike** [comment]
You need to jusst disable strictMode and it will render once
![image](https://github.com/XantreGodlike/preact-signals/assets/57757211/15455b99-5858-4096-984f-5e89565ee132)

![image](https://github.com/XantreGodlike/preact-signals/assets/57757211/62cee741-32a4-493d-926f-e2d3c6248302)

**Comment by qingzhoufeihu** [comment]
Thank you very much, it works.

**Comment by ankitkaushik24** [comment]
It's worth noting that the issue is specific to strict mode, which is a feature in React that helps detect potential problems in an application. Disabling strict mode can help resolve the issue, but it's generally recommended to keep strict mode enabled in development to catch any potential issues.

Hence, I still believe its an issue to be resolved.
